### ISSUE TITLE
[TODO] Game : 10 Scenarii for Battle IA

### ISSUE THREAD

**Issue by blenderlab** [blenderlab/BattleIA#16]
To be more fun, we need to implement scenarii in Battle IA.

A scenario must contain : 

- Size of terrain
- Number of players (min/max)
- Objective(s)
- Scoring method
- History (story telling) 

As you will try not to update too much the existing code, you can add features.
Please quote the modifications that will have to be done on the server side or bot side : 

- new functionality 
- new messages 
- new ???

**Comment by ghost** [comment]
Groupe 0 ( Théo , Clément et Julien )

**Comment by blenderlab** [comment]
and now ?

**Comment by ghost** [comment]
it's just to reserve the task and therefore not be several groups who work on the same task.

**Comment by ghost** [comment]
did we must use git in stead of word for exemple , because scenarii are doesn't force to use git

**Comment by blenderlab** [comment]
> did we must use git in stead of word for exemple , because scenarii are doesn't force to use git

Start with any kind of document you want.
Each scenario will then be integrated in the wiki or/.and website (lately)

**Comment by ghost** [comment]
ok thanks !

**Comment by blenderlab** [comment]
7 maps done. With new features. Seems good !

**Comment by rfleuryleveso** [comment]
A map editor is available: https://github.com/rfleuryleveso/battleia-mapmaker
