### ISSUE TITLE
[TODO] BattleIA : Logo for BattleIA

### ISSUE THREAD

**Issue by blenderlab** [blenderlab/BattleIA#18]
IT lacks a logo for the game. It has to be corrected ;-D

**Comment by callme-sy** [comment]
Je verrai bien quelque chose dans ce style mais en mieux, car à part fusionner des images sur gimp je suis pas très doué : 
![nodes (3)](https://user-images.githubusercontent.com/55266056/96450506-9860e700-1216-11eb-861d-f31eca631512.jpg)

![nodesxelectric_logo_BattleIA](https://user-images.githubusercontent.com/55266056/96450517-9c8d0480-1216-11eb-847d-8d1f34aae595.jpg)

**Comment by blenderlab** [comment]
I like the first one, Would it be possible to add a robot or just a robot head isntead of the lightning ? 
Like this https://dribbble.com/shots/2485370-Robot ?

**Comment by blenderlab** [comment]
Nice logo done !
